minor fixes/changes

diff --git a/bin/vs b/bin/vs
--- a/bin/vs
+++ b/bin/vs
@@ -1,8 +1,8 @@
 #!/bin/bash
 
 err () {
-   echo "ERR: $1" 
-   exit 1
+    printf "%s [ERROR]: %s\n" "$0" "$1" >&2
+    exit 1
 }
 
 session="$1"
